export const GET_ITEMS='GET_ITEMS';
export const ADD_ITEM='ADD_ITEM';
export const DELETE_ITEM='DELETE_ITEM';
export const ITEMS_LOADING='ITEMS_LOADING';
export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';
export const EDIT_ITEM='EDIT_ITEM';
export const ADD_MESSAGE='ADD_MESSAGE';

//ADMIN
export const ADMIN_LOADING='ADMIN_LOADING';
export const ADMIN_LOADED='ADMIN_LOADED';
export const ADMIN_LOGIN_SUCCESS='ADMIN_LOGIN_SUCCESS';
export const ADMIN_REGISTER_SUCCESS='ADMIN_REGISTER_SUCCESS';
export const ADMIN_AUTH_ERROR='ADMIN_AUTH_ERROR';
export const ADMIN_LOGIN_FAIL='ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT_SUCCESS='ADMIN_LOGOUT_SUCCESS';
export const ADMIN_REGISTER_FAIL='ADMIN_REGISTER_FAIL';





